export type GameConfig = {
  ctx: CanvasRenderingContext2D;
  canvasWidth: number;
  canvasHeight: number;
  playerSize: number;
  playerColor: string;
  playerName: string;
  gameSpeed: number;
  showGrid: boolean;
  playerHead: {x: number, y: number}[];
  speed: number;
  directionX: number;
  directionY: number;
  lastKey: string;
  directionLock: boolean;
  foodColor: string;
  foodX: number;
  foodY: number;
  animationFrameID: number;
  lastTime: number;
  isGameOver: boolean;
};
